export const committeeMembers = [
  // Key Members (5)
  {
    id: 1,
    name: "Dr. Rajesh Sharma",
    position: "President",
    image: "/confident-businessman.png",
    email: "president@community.org",
    phone: "+1 (555) 123-4567",
    bio: "Leading our community with vision and dedication for over 15 years.",
    tier: "key",
  },
  {
    id: 2,
    name: "Priya Patel",
    position: "Vice President",
    image: "/confident-professional.png",
    email: "vp@community.org",
    phone: "+1 (555) 234-5678",
    bio: "Passionate about cultural preservation and community growth.",
    tier: "key",
  },
  {
    id: 3,
    name: "Amit Singh",
    position: "General Secretary",
    image: "/confident-professional.png",
    email: "secretary@community.org",
    phone: "+1 (555) 345-6789",
    bio: "Coordinating all community activities with precision and care.",
    tier: "key",
  },
  {
    id: 4,
    name: "Neha Gupta",
    position: "Treasurer",
    image: "/confident-professional.png",
    email: "treasurer@community.org",
    phone: "+1 (555) 456-7890",
    bio: "Managing our finances with transparency and strategic planning.",
    tier: "key",
  },
  {
    id: 5,
    name: "Vikram Mehta",
    position: "Joint Secretary",
    image: "/confident-businessman.png",
    email: "jointsec@community.org",
    phone: "+1 (555) 567-8901",
    bio: "Supporting our administrative functions and special initiatives.",
    tier: "key",
  },
]

export const trustees = [
  {
    id: 1,
    name: "Mohan Desai",
    position: "Chairperson",
    image: "/placeholder.svg?height=150&width=150&query=elderly%20man%20in%20formal%20attire",
    term: "2020-2025",
    bio: "Serving the community for over 25 years with dedication and vision.",
    achievements: ["Expanded community center", "Established scholarship fund", "Created senior citizen program"],
  },
  {
    id: 2,
    name: "Lakshmi Iyer",
    position: "Vice Chairperson",
    image: "/placeholder.svg?height=150&width=150&query=elderly%20woman%20in%20formal%20attire",
    term: "2020-2025",
    bio: "A passionate advocate for education and cultural preservation.",
    achievements: [
      "Led cultural preservation initiative",
      "Developed youth mentorship program",
      "Organized annual heritage festival",
    ],
  },
  {
    id: 3,
    name: "Arjun Nair",
    position: "Trustee",
    image: "/placeholder.svg?height=150&width=150&query=middle%20aged%20man%20in%20business%20suit",
    term: "2022-2027",
    bio: "Bringing financial expertise and strategic planning to our community.",
    achievements: [
      "Restructured financial systems",
      "Secured major donations",
      "Implemented long-term investment strategy",
    ],
  },
  {
    id: 4,
    name: "Sunita Kapoor",
    position: "Trustee",
    image: "/placeholder.svg?height=150&width=150&query=middle%20aged%20woman%20professional",
    term: "2021-2026",
    bio: "Dedicated to community outreach and social welfare initiatives.",
    achievements: [
      "Created food bank program",
      "Established health clinic partnership",
      "Developed community emergency response team",
    ],
  },
  {
    id: 5,
    name: "Rahul Malhotra",
    position: "Trustee",
    image: "/placeholder.svg?height=150&width=150&query=professional%20man%20with%20beard",
    term: "2023-2028",
    bio: "Focused on youth development and modernizing community programs.",
    achievements: [
      "Launched digital literacy program",
      "Created STEM education initiative",
      "Developed sports complex",
    ],
  },
]

export const pastLeadership = {
  presidents: [
    {
      id: 1,
      name: "Dr. Anil Kumar",
      image: "/placeholder.svg?height=150&width=150&query=elderly%20man%20with%20glasses",
      term: "2020-2022",
      achievements: "Led community through pandemic, established online programs",
    },
    {
      id: 2,
      name: "Meera Joshi",
      image: "/placeholder.svg?height=150&width=150&query=elderly%20woman%20smiling",
      term: "2018-2020",
      achievements: "Expanded cultural programs, renovated community center",
    },
    {
      id: 3,
      name: "Suresh Menon",
      image: "/placeholder.svg?height=150&width=150&query=senior%20man%20in%20formal%20attire",
      term: "2016-2018",
      achievements: "Established scholarship fund, increased membership by 30%",
    },
    {
      id: 4,
      name: "Kavita Rao",
      image: "/placeholder.svg?height=150&width=150&query=senior%20woman%20in%20professional%20attire",
      term: "2014-2016",
      achievements: "Launched annual cultural festival, improved financial stability",
    },
  ],
  trustees: [
    {
      id: 1,
      name: "Vijay Sharma",
      image: "/placeholder.svg?height=150&width=150&query=elderly%20man%20in%20suit",
      term: "2015-2020",
      achievements: "Oversaw major expansion of community facilities",
    },
    {
      id: 2,
      name: "Deepa Agarwal",
      image: "/placeholder.svg?height=150&width=150&query=elderly%20woman%20in%20traditional%20attire",
      term: "2010-2020",
      achievements: "Established endowment fund for community sustainability",
    },
    {
      id: 3,
      name: "Ravi Krishnan",
      image: "/placeholder.svg?height=150&width=150&query=senior%20man%20with%20white%20hair",
      term: "2005-2015",
      achievements: "Led acquisition of current community center property",
    },
  ],
  secretaries: [
    {
      id: 1,
      name: "Nisha Patel",
      image: "/placeholder.svg?height=150&width=150&query=middle%20aged%20woman%20with%20glasses",
      term: "2020-2022",
      achievements: "Digitized all community records and communications",
    },
    {
      id: 2,
      name: "Kiran Shah",
      image: "/placeholder.svg?height=150&width=150&query=middle%20aged%20man%20smiling",
      term: "2018-2020",
      achievements: "Established regular newsletter and improved member engagement",
    },
    {
      id: 3,
      name: "Anjali Mathur",
      image: "/confident-professional.png",
      term: "2016-2018",
      achievements: "Streamlined event management processes",
    },
  ],
}
