export const facilityData = [
  {
    id: "1",
    name: "Community Hall",
    description: "A spacious hall for community events.",
    availability: "available",
    imageUrl: "/placeholder.svg",
    location: "Main Street",
    capacity: "200",
    status: "active",
    type: "hall",
  },
  {
    id: "2",
    name: "Sports Complex",
    description: "A modern sports complex with various facilities.",
    availability: "maintenance",
    imageUrl: "/placeholder.svg",
    location: "Park Avenue",
    capacity: "500",
    status: "active",
    type: "sports",
  },
  {
    id: "3",
    name: "Community Hostel",
    description: "Affordable hostel for community members.",
    availability: "available",
    imageUrl: "/placeholder.svg",
    location: "Near the University",
    capacity: "100",
    status: "active",
    type: "hostels",
  },
  {
    id: "4",
    name: "Book Bank",
    description: "A collection of books available for community members.",
    availability: "available",
    imageUrl: "/placeholder.svg",
    location: "Library",
    capacity: "N/A",
    status: "active",
    type: "book-bank",
  },
  {
    id: "5",
    name: "Community Gym",
    description: "A well-equipped gym for community members.",
    availability: "available",
    imageUrl: "/placeholder.svg",
    location: "Sports Complex",
    capacity: "50",
    status: "active",
    type: "gym",
  },
  {
    id: "6",
    name: "Astrology Center",
    description: "Astrology services for community members.",
    availability: "available",
    imageUrl: "/placeholder.svg",
    location: "Temple",
    capacity: "10",
    status: "active",
    type: "astrology",
  },
  {
    id: "7",
    name: "Party Plot 1",
    description: "A party plot for community events.",
    availability: "available",
    imageUrl: "/placeholder.svg",
    location: "Near the River",
    capacity: "300",
    status: "active",
    type: "party-plots",
  },
]

export const memberData = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "123-456-7890",
    membershipType: "regular",
    joinDate: "2023-01-15",
    status: "active",
    profileImage: "/placeholder.svg",
    hasVerificationRequest: false,
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "987-654-3210",
    membershipType: "lifetime",
    joinDate: "2022-05-20",
    status: "active",
    profileImage: "/placeholder.svg",
    hasVerificationRequest: true,
  },
  {
    id: "3",
    name: "Alice Brown",
    email: "alice.brown@example.com",
    phone: "111-222-3333",
    membershipType: "regular",
    joinDate: "2023-03-10",
    status: "active",
    profileImage: "/placeholder.svg",
    hasVerificationRequest: false,
  },
  {
    id: "4",
    name: "Bob Wilson",
    email: "bob.wilson@example.com",
    phone: "444-555-6666",
    membershipType: "senior",
    joinDate: "2022-11-01",
    status: "inactive",
    profileImage: "/placeholder.svg",
    hasVerificationRequest: false,
  },
  {
    id: "5",
    name: "Carol Martinez",
    email: "carol.martinez@example.com",
    phone: "777-888-9999",
    membershipType: "student",
    joinDate: "2023-09-01",
    status: "pending",
    profileImage: "/placeholder.svg",
    hasVerificationRequest: true,
  },
]
